before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Wgkg4hr+aMnQ74fClfBDkzkMhwrhgxNuEbknqltpqKfnz8iDNcuct4y586IkgTg214L9wVyf0hVDBgWs/dRFpAbkialAbv754QdRlkLr20AItJfQoyaA2C5Ylcq0LlqkxpjbPJyPp2Ow0SXhZgA1bQbHv9L+CzoGogDW6Qkv6A6SrLhaZMT1I1MOhgnNYCJkXJuGUGesLVbQhU050x+zR61cT9vxVCnA2ZK2qD+L1KuJklB/Js+vmhPDXnhN8lcgbin9NstSTQCWcLuorK7iljoC4Vvo5DuURyPBRrx5ZijB99oeNSD8P8bMNSwfCpsrfiyWAgsHt+vbaEJ7TR3UrZsoMXB9h1/JikPjpyE8s0c+Sn5YxvOp+bYLjkDvCj/VWKW2rgtl9K80FptcA0kzluzf2wj+qI7C4s43al3lD6SjJmDgrhB9l2GB3WOdaF8yHit0iLQsP/zSdSk864X7NdLgFWeqkg/JvxtAWonIcAl4Q5DJDgYd3Bvvsg2i2p3VOUjT3dldk0pCxLHzlO2k6/Mzj+CymHZLEqXSvIq6P12g/VHgqTgBvCdMXmTU6hqN1VG8LS9UcCLZupUXDCmzO0icg/tp8UQd1+8WY6SuGJZlZYLrx2P4H1kemyP01Tod2zaggTGV1nlNreiOnA0GM+wibXE3hyRuhBXM3RumS7M= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
